const courts = [
  { courtId: '34455243',
    courtTitle: 'Вінницький окружний адміністративний суд',
    courtAddress: '21001, місто Вінниця, вулиця Брацлавська, 14',
    courtEmail: 'inbox@adm.vn.court.gov.ua' },
  { courtId: '35123898',
    courtTitle: 'Волинський окружний адміністративний суд',
    courtAddress: '43025, Волинська область, місто Луцьк, вулиця Словацького, 3',
    courtEmail: 'inbox@adm.vl.court.gov.ua' },
  { courtId: '34824364',
    courtTitle: 'Дніпропетровський окружний адміністративний суд',
    courtAddress: '49089, Дніпропетровська область, місто Дніпро, вулиця Академіка Янгеля, 4',
    courtEmail: 'inbox@adm.dp.court.gov.ua' },
  { courtId: '35099148',
    courtTitle: 'Донецький окружний адміністративний суд',
    courtAddress: '84122, Донецька область,  місто Слов\'янськ, вулиця Добровольського, 1',
    courtEmail: 'inbox@adm.dn.court.gov.ua' },
  { courtId: '34854954',
    courtTitle: 'Житомирський окружний адміністративний суд',
    courtAddress: '10014, місто Житомир, вулиця Мала Бердичівська, 23 ',
    courtEmail: 'inbox@adm.zt.court.gov.ua' },
  { courtId: '35231455',
    courtTitle: 'Закарпатський окружний адміністративний суд',
    courtAddress: '88017, Закарпатська область, місто Ужгород, вулиця Загорська, 30',
    courtEmail: 'inbox@adm.zk.court.gov.ua' },
  { courtId: '35450335',
    courtTitle: 'Запорізький окружний адміністративний суд',
    courtAddress: ' 69041, місто Запоріжжя, вулиця Сергія Синенка, 65-В',
    courtEmail: 'inbox@adm.zp.court.gov.ua' },
  { courtId: '35021574',
    courtTitle: 'Івано-Франківський окружний адміністративний суд',
    courtAddress: '76018, місто Івано-Франківськ, вулиця Незалежності 46 ',
    courtEmail: 'inbox@adm.if.court.gov.ua' },
  { courtId: '35919304',
    courtTitle: 'Київський окружний адміністративний суд',
    courtAddress: '01133, місто Київ, бульвар Лесі Українки, 26',
    courtEmail: 'inbox@adm.ko.court.gov.ua' },
  { courtId: '35084241',
    courtTitle: 'Кіровоградський окружний адміністративний суд',
    courtAddress: '25006, Кіровоградська область,  місто Кропивницький, вулиця Велика Перспективна, 40',
    courtEmail: 'inbox@adm.kr.court.gov.ua' },
  { courtId: '35079949',
    courtTitle: 'Луганський окружний адміністративний суд',
    courtAddress: '93400, Луганська область, місто Сєвєродонецьк, проспект  Космонавтів, 18',
    courtEmail: 'inbox@adm.lg.court.gov.ua' },
  { courtId: '35775334',
    courtTitle: 'Львівський окружний адміністративний суд',
    courtAddress: '79018, місто Львів, вулиця Чоловського, 2',
    courtEmail: 'inbox@adm.lv.court.gov.ua' },
  { courtId: '35356555',
    courtTitle: 'Миколаївський окружний адміністративний суд',
    courtAddress: '54001, місто Миколаїв, вул Декабристів, 41/10 ',
    courtEmail: 'inbox@adm.mk.court.gov.ua' },
  { courtId: '35118626',
    courtTitle: 'Одеський окружний адміністративний суд',
    courtAddress: '65062, місто Одеса, вулиця Фонтанська дорога, буд. 14',
    courtEmail: 'inbox@adm.od.court.gov.ua' },
  { courtId: '35521510',
    courtTitle: 'Полтавський окружний адміністративний суд',
    courtAddress: ' 36039, місто Полтава, вулиця Пушкарівська, 9/26 ',
    courtEmail: 'inbox@adm.pl.court.gov.ua' },
  { courtId: '34847329',
    courtTitle: 'Рівненський окружний адміністративний суд',
    courtAddress: '33028, місто Рівне, вулиця 16 Липня, 87',
    courtEmail: 'inbox@adm.rv.court.gov.ua ' },
  { courtId: '35907252',
    courtTitle: 'Сумський окружний адміністративний суд',
    courtAddress: '40021, місто Суми, вулиця Герасима Кондратьєва, 159',
    courtEmail: ' inbox@adm.su.court.gov.ua' },
  { courtId: '35157712',
    courtTitle: 'Тернопільський окружний адміністративний суд',
    courtAddress: '46021, місто Тернопіль, вулиця Грушевського, 6',
    courtEmail: 'inbox@adm.te.court.gov.ua' },
  { courtId: '34390710',
    courtTitle: 'Харківський окружний адміністративний суд',
    courtAddress: '61022, місто Харків, майдан Свободи, 6',
    courtEmail: 'inbox@adm.hr.court.gov.ua' },
  { courtId: '35330156',
    courtTitle: 'Херсонський окружний адміністративний суд',
    courtAddress: '73027, місто Херсон, вулиця Філатова, 29',
    courtEmail: 'inbox@adm.ks.court.gov.ua' },
  { courtId: '35173158',
    courtTitle: 'Хмельницький окружний адміністративний суд',
    courtAddress: '29009, місто Хмельницький, вулиця Козацька, 42',
    courtEmail: 'inbox@adm.km.court.gov.ua' },
  { courtId: '35158674',
    courtTitle: 'Черкаський окружний адміністративний суд',
    courtAddress: '18002, місто Черкаси, бульвар Шевченка, 117',
    courtEmail: 'inbox@adm.ck.court.gov.ua' },
  { courtId: '35891723',
    courtTitle: 'Чернівецький окружний адміністративний суд',
    courtAddress: '58001, місто Чернівці, вулиця Садова, 1-І',
    courtEmail: 'inbox@adm.cv.court.gov.ua' },
  { courtId: '35108650',
    courtTitle: 'Чернігівський окружний адміністративний суд',
    courtAddress: '14005, місто Чернігів, вулиця Київська, 23  ',
    courtEmail: 'inbox@adm.cn.court.gov.ua ' },
  { courtId: '34414689',
    courtTitle: 'Окружний адміністративний суд міста Києва',
    courtAddress: '03150, місто Київ, вулиця Велика Васильківська, 81А',
    courtEmail: 'inbox@adm.ki.court.gov.ua' }
]

module.exports = courts
